openapi: 3.0.0
info:
  version: 1.0.0
  title: e-commerce service Inditex
  description: Product prices consult service
servers:
  - url: http://localhost:8080
    description: local server
tags:
  - name: product prices
    description: consult the prices of a product
paths:
  /product-prices:
    get:
      summary: Consult the price of a product on a given date
      tags:
        - product prices
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
          required: true
          description: Date application
        - in: query
          name: ProductId
          schema:
            type: integer
          required: true
          description: Product identifier
        - in: query
          name: BrandId
          schema:
            type: integer
          required: true
          description: Brand identification (example 1 = ZARA).
      responses:
        '200':
          description: Is OK. Return final price product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricesResponse"
        '400':
          description: Incorrect request
        '404':
          description: No tariff was found for the requested product, brand and date
components:
  schemas:
    PricesResponse:
      type: object
      properties:
        productId:
          type: integer
        brandId:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        tariff:
          type: integer
        finalPrice:
          type: number
          format: float
