openapi: 3.0.0
info:
  version: 1.0.0
  title: e-commerce service Inditex
  description: Product prices consult service
servers:
  - url: http://localhost:8080
    description: local server
tags:
  - name: Product prices
    description: consult the prices of a product
paths:
  /productPrices:
    get:
      operationId: productPrices
      tags:
        - Product prices
      summary: Consult the price of a product on a given date
      parameters:
        - name: applicationDate
          in: query
          required: true
          schema:
            type: OffsetDateTime
          example: 2020-06-14T10:00:00.000
          description: Date in format YYYY-MM-dd'T'HH:mm:ss
        - name: product
          in: query
          required: true
          schema:
            type: integer
          description: Product identification
        - name: brand
          in: query
          required: true
          schema:
            type: integer
          description: Brand identification (example 1 = ZARA).
      responses:
        '200':
          description: Is OK. Return final price product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricesResponse"
        '400':
          description: Incorrect request
        '404':
          description: No tariff was found for the requested product, brand and date
components:
  schemas:
    PricesResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: OffsetDateTime
        endDate:
          type: OffsetDateTime
        price:
          type: string